server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://prod-db-cluster:3306/order_db
logging:
  level:
    com.example.order: INFO
external:
  payment:
    url: https://api.payment.prod.com/process
